# Builds the website when pushed to main, and put's the result into the /docs directory
name: build when pushed to main



# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write # access to check out code and install dependencies
      pages: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: ./webfix.py -f libregraphicsmeeting.org docs
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - run: npm install markdown-it
      - run: npx @11ty/eleventy
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A docs
          git commit -m "gh action to put build result in docs"
          git push
